version: '3.9'
services:
  db:
    image: postgres:16
    container_name: simpledrive_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: simpledrive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: simpledrive_redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
  ftp:
    image: delfer/alpine-ftp-server
    container_name: simpledrive-ftp
    restart: unless-stopped
    ports:
      - '21:21'
      - '30000-30009:30000-30009'
    environment:
      USERS: 'ftpuser|ftppass'
      ADDRESS: '127.0.0.1'
      MIN_PORT: 30000
      MAX_PORT: 30009
    volumes:
      - ./ftp-data:/ftp/ftpuser
volumes:
  db_data:
