version: '3.9'
services:
  db:
    image: postgres:16
    container_name: simpledrive_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: simpledrive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: simpledrive_redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
volumes:
  db_data:
